account/urls.py
from django.contrib.auth import views
from django.urls import path
from django.conf.urls import include

from .views import (
    ArticleList,
    article_create_view,
    ArticleUpdate,
    ArticleDelete,
    AddVakil,
    vakileList,
    Riyasatlist,
    vakil_image_view,
    add_comision,
    ComisionDetail, CustomLoginView, ComisionView, VakilUpdateView, VakilDeleteView, RiyasatDeleteView,
    add_riyasat, comision_edit, comision_delete, contact_view,success_page,MessageUpdateView,MessageListView,delete_article_image
)


app_name = 'account'

urlpatterns = [
	path('', ArticleList.as_view(), name="home"),
	path('vakillist/', vakileList.as_view(), name="vakil_list"),
    path('vakil/edit/<int:pk>/', VakilUpdateView.as_view(), name = 'vakil_edit'),
    path('vakil/delete/<int:pk>/', VakilDeleteView.as_view(), name = 'vakil_delete'),
    path('comisiondetail/<int:id>', ComisionDetail.as_view(), name="comision_detail"),
	path('riyasatlist/', Riyasatlist.as_view(), name="riyasat_list"),
	path('addvakil/', AddVakil.as_view(), name="vakil_add"),
    path('add-riyasat/', add_riyasat, name = 'add_riyasat'),
    path('addcomision/', add_comision, name="comision_add"),
    path('article/create/', article_create_view, name="create_article"),
    path('comision/', ComisionView.as_view(), name = "comision"),
    path('article/update/<int:pk>', ArticleUpdate.as_view(), name="article_update"),
	path('article/delete/<int:pk>', ArticleDelete.as_view(), name="article_delete"),
    path('image_upload/<int:id>/', vakil_image_view.as_view(), name = 'image_upload'),
    path('login/', CustomLoginView.as_view(), name = 'login'),
    path('comision/edit/<int:pk>/', comision_edit, name='comision_edit'),
    path('comision/delete/<int:pk>/', comision_delete, name='comision_delete'),
    path('riyasat/delete/<int:pk>/', RiyasatDeleteView.as_view(), name = 'riyasat_delete'),
    path('contact/', contact_view, name = 'contact'),
    path('contact/success/', success_page, name = 'success_page'),
    path('messages/', MessageListView.as_view(), name = 'message_list'),
    path('admin/messages/<int:pk>/', MessageUpdateView.as_view(), name = 'message_update'),
path('delete-article-image/<int:image_id>/', delete_article_image, name='delete-article-image'),
]

djangohmdbar/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('modir/account/', admin.site.urls),
    path('', include('home.urls', namespace = 'home')),
    path('account/modir/', include('account.urls', namespace = 'account')),
    path('captcha/', include('captcha.urls')),
    path('ckeditor5/', include('django_ckeditor_5.urls')),

]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path
from .views import (
	ArticleList,
	ArticleDetail,
	ArticlePreview,
	CategoryList,
	VokalaView,
	VakilCity,
	VakilPage,
	ArticleSearchList,
	UploadExcelView

)
app_name = "home"
urlpatterns = [
	path('upload-excel/', UploadExcelView.as_view(), name = 'upload_excel'),
	path('', ArticleList.as_view(), name="home"),
	# path('page/<int:page>/', ArticleList.as_view(), name="home"),
	path('article/<slug:slug>/', ArticleDetail.as_view(), name="detail"),
	path('vokala/', VokalaView.as_view(), name="vokala"),
	path('city/<str:city>/', VakilCity.as_view(), name="vokala_city"),
	path('preview/<int:pk>/', ArticlePreview.as_view(), name="preview"),
	path('vakil/<int:id>/', VakilPage.as_view(), name="vakil"),
	path('category/<slug:slug>/', CategoryList.as_view(), name="category"),
	path('category/<slug:slug>/page/<int:page>/', CategoryList.as_view(), name="category"),
	path('search/', ArticleSearchList.as_view(), name = 'search_articles'),

]

templates/inc/messages.html
{% if messages %}
    {% for msg in messages %}
        <p class="alert alert-{{ msg.tags }}">{{ msg }}</p>
    {% endfor %}
{% endif %}

templates/inc/navbar.html
{% load static %}
<div class="container-fluid position-relative p-0">
    <nav class="navbar navbar-expand-lg navbar-light px-4 px-lg-5 py-3 py-lg-0">
        <a href="" class="navbar-brand p-0">
            <div class="row">
                <div>
                    <img src="{% static 'asset/img/logo.png' %}" alt="Logo" style="width: 100px; height: 50px;">
                </div>
            </div>
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
            <div class="navbar-nav ms-auto py-0">
                <li><a class="nav-link scrollto active" href="#hero" style="font-family: Sahel; color: #0b1281;">صفحه اصلی</a></li>
                <li><a class="nav-link scrollto" href="#news" style="font-family: Sahel; color: #0b1281;" >اخبار</a></li>
                <li><a class="nav-link scrollto" href="{% url 'home:vokala' %}" style="font-family: Sahel; color: #0b1281;">جستجوی وکیل</a></li>
                <li><a class="nav-link scrollto" href="#riyast" style="font-family: Sahel; color: #0b1281;">هیات مدیره</a></li>
                <div class="nav-item dropdown" style="font-family: Sahel; color: #0b1281;">
                    <a href="#" class="nav-link" data-bs-toggle="dropdown" style="font-family: Sahel; color: #0b1281;">
                        <span class="dropdown-toggle" style="font-family: Sahel; color: #0b1281;">کمیسیون ها</span>
                    </a>
                   <div class="dropdown-menu">
    {% for i in comi %}
    <a href="{% url 'account:comision_detail' i.id %}" class="dropdown-item" style="font-family: Sahel; color: #073270;">
        {{ i.name }}
    </a>
    {% endfor %}
</div>
                </div>
            </div>
        </div>
    </nav>

    <!-- Carousel Start -->
    <div class="header-carousel owl-carousel">
        <div class="header-carousel-item">
            <img src="{% static 'back.jpg' %}" class="img-fluid" style="width: 100%;" alt="Image">
            <div class="carousel-caption">
                <div class="container">
                    <div class="row gy-0 gx-5">
                        <div class="col-lg-0 col-xl-5"></div>
                        <div class="col-xl-7 animated fadeInLeft">
                            <div class="text-sm-center text-md-end">
                                <h4 class="text-uppercase fw-bold mb-4" style="font-family: 'B Titr'; font-size: 55px;"></h4>
                                <div class="d-flex align-items-center justify-content-center justify-content-md-end"></div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="header-carousel-item">
            <img src="{% static 'aks.jpg' %}" class="img-fluid" style="width: 100%;" alt="Image">
            <div class="carousel-caption">
                <div class="container">
                    <div class="row g-5">
                        <div class="col-12 animated fadeInUp">
                            <div class="text-center"></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="header-carousel-item">
            <img src="{% static 'night.jpg' %}" class="img-fluid" style="width: 100%;" alt="Image">
            <div class="carousel-caption">
                <div class="container">
                    <div class="row g-5">
                        <div class="col-12 animated fadeInUp">
                            <div class="text-center"></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Carousel End -->
</div>

templates/inc/search_box.html
<!-- templates/inc/search_box.html -->
<div class="container mb-5">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <form method="GET" action="{% url 'home:search_articles' %}" class="search-form">
                <div class="input-group">
                    <input
                        type="text"
                        name="q"
                        class="form-control"
                        placeholder="جستجو در اخبار..."
                        aria-label="Search"
                        value="{{ query }}"
                    >
                    <button class="btn btn-primary" type="submit">
                        <i class="fas fa-search"></i>
                    </button>
                </div>
            </form>
        </div>
    </div>
</div>

templates/inc/sidebar.html
{% load static %}

<aside class="main-sidebar sidebar-dark-primary elevation-4">
  <!-- Brand Logo -->
  <a href="#" class="brand-link text-center">
    <span class="brand-text" style="font-family: 'B Titr'; font-size: 14px;">کانون وکلای دادگستری استان همدان</span>
  </a>

  <!-- Sidebar -->
  <div class="sidebar">
    <nav class="mt-2" style="font-family: 'Sahel';">
      <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">

        <!-- اخبار -->
        <li class="nav-item has-treeview">
          <a href="#" class="nav-link active">
            <i class="nav-icon fa fa-newspaper"></i>
            <p>اخبار<i class="right fas fa-angle-left"></i></p>
          </a>
          <ul class="nav nav-treeview">
            <li class="nav-item">
              <a href="{% url 'account:home' %}" class="nav-link">
                <i class="fa fa-list nav-icon"></i>
                <p>لیست اخبار</p>
              </a>
            </li>
            <li class="nav-item">
              <a href="{% url 'account:create_article' %}" class="nav-link">
                <i class="fa fa-plus-square nav-icon"></i>
                <p>افزودن خبر</p>
              </a>
            </li>
          </ul>
        </li>

        <!-- وکلا -->
        <li class="nav-item has-treeview">
          <a href="{% url 'account:vakil_list' %}" class="nav-link active">
            <i class="nav-icon fa fa-user"></i>
            <p>وکلا<i class="right fas fa-angle-left"></i></p>
          </a>
          <ul class="nav nav-treeview">
            <li class="nav-item">
              <a href="{% url 'account:vakil_list' %}" class="nav-link">
                <i class="fa fa-list nav-icon"></i>
                <p>لیست وکلا</p>
              </a>
            </li>
            <li class="nav-item">
              <a href="{% url 'account:vakil_add' %}" class="nav-link">
                <i class="fa fa-plus-square nav-icon"></i>
                <p>افزودن وکیل</p>
              </a>
            </li>
          </ul>
        </li>

        <!-- هیات مدیره -->
        <li class="nav-item has-treeview">
          <a href="{% url 'account:riyasat_list' %}" class="nav-link active">
            <i class="nav-icon fa fa-users"></i>
            <p>هیات مدیره<i class="right fas fa-angle-left"></i></p>
          </a>
          <ul class="nav nav-treeview">
            <li class="nav-item">
              <a href="{% url 'account:riyasat_list' %}" class="nav-link">
                <i class="fa fa-list nav-icon"></i>
                <p>لیست هیات مدیره</p>
              </a>
            </li>
            <li class="nav-item">
              <a href="{% url 'account:add_riyasat' %}" class="nav-link">
                <i class="fa fa-plus-square nav-icon"></i>
                <p>افزودن عضو</p>
              </a>
            </li>
          </ul>
        </li>

        <!-- کمیسیون‌ها -->
        <li class="nav-item has-treeview">
          <a href="{% url 'account:comision' %}" class="nav-link active">
            <i class="nav-icon fa fa-sitemap"></i>
            <p>کمیسیون‌ها<i class="right fas fa-angle-left"></i></p>
          </a>
          <ul class="nav nav-treeview">
            <li class="nav-item">
              <a href="{% url 'account:comision' %}" class="nav-link">
                <i class="fa fa-list nav-icon"></i>
                <p>لیست کمیسیون‌ها</p>
              </a>
            </li>
            <li class="nav-item">
              <a href="{% url 'account:comision_add' %}" class="nav-link">
                <i class="fa fa-plus-square nav-icon"></i>
                <p>افزودن کمیسیون</p>
              </a>
            </li>
          </ul>
        </li>

        <!-- پیام‌ها -->
        <li class="nav-item has-treeview">
          <a href="{% url 'account:message_list' %}" class="nav-link active">
            <i class="nav-icon fa fa-envelope"></i>
            <p>پیام‌ها<i class="right fas fa-angle-left"></i></p>
          </a>
          <ul class="nav nav-treeview">
            <li class="nav-item">
              <a href="{% url 'account:message_list' %}" class="nav-link">
                <i class="fa fa-list nav-icon"></i>
                <p>لیست پیام‌ها</p>
              </a>
            </li>
          </ul>
        </li>

      </ul>
    </nav>
  </div>
</aside>